-- Migration: initial_schema
-- Project: GenZ-Cap-Store
-- Generated by: Database Engineer Agent

BEGIN;

-- ── TABLES ──────────────────────────────────────────────────────────────────

-- Table: leads
-- Description: Stores waitlist signups for future drops
CREATE TABLE IF NOT EXISTS public.leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    full_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    email_address TEXT NOT NULL UNIQUE,
    status TEXT DEFAULT 'waitlist'
);

-- ── ROW LEVEL SECURITY ───────────────────────────────────────────────────────

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anonymous service-side inserts (via Service Role) 
-- OR specific public insert policy
CREATE POLICY "Enable insert for everyone" ON public.leads
    FOR INSERT WITH CHECK (true);

-- Policy: Only authenticated admins can view lead data
CREATE POLICY "Admins can view leads" ON public.leads
    FOR SELECT USING (auth.role() = 'service_role');

COMMIT;